---
title: "Dan Warren"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

# About Me

I have broad interests across evolution, ecology, biogeography, and conservation biology.  My primary research program focuses on using informatics approaches to answer large-scale questions in population biology, with a particular focus on species distribution models/environmental niche models.  I also have active research programs in phylogenetic methods and theory, and neuroecology of marine fishes.  I tend to do a lot of quantitative and computational methods development, and have developed several widely-used software packages for population biologists.




# Publications (last updated `r Sys.Date()`)

For the most up-to-date information on what I've been doing, check [Google Scholar](http://scholar.google.com/citations?user=NTzu9c8AAAAJ&hl=en).  You can also check me out on [Orcid](http://orcid.org/0000-0002-8747-2451), [ResearcherID](http://www.researcherid.com/rid/B-3821-2010), or [Scopus](http://www.scopus.com/authid/detail.url?authorId=7202133982), but those are updated considerably less often.
<br>

```{r citations, echo = FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=60), results="asis"}
library(rcrossref)
library(pander)
library(scholar)

# Note to self: currently no doi for the new accepted gecko thing, check back

# dois <- c("10.1093/gbe/evw171",
#           "10.1111/geb.12455",
#           "10.1111/gcb.13038",
#           "10.1093/molbev/msv137",
#           "10.1111/jeb.12631",
#           "10.1016/j.tree.2014.08.003",
#           "10.1111/ddi.12160",
#           "10.1016/j.tree.2013.02.003",
#           "10.1016/j.ympev.2012.07.020",
#           "10.1016/j.tree.2012.03.010",
#           "10.1111/j.1420-9101.2012.02503.x",
#           "10.1093/gbe/evs013",
#           "10.3374/014.052.0106",
#           "10.1890/10-1171.1",
#           "10.1073/pnas.1015806108",
#           "10.1111/j.1558-5646.2010.01177.x",
#           "10.1371/journal.pone.0015297",
#           "10.1111/j.1600-0587.2009.06142.x",
#           "10.3732/ajb.0900216",
#           "10.1093/sysbio/syp019",
#           "10.1111/j.1558-5646.2008.00482.x",
#           "10.1093/bioinformatics/btm388",
#           "10.1080/10635150500431155",
#           "10.1021/bi983033o")
# 
# cites <- unlist(cr_cn(dois, format = "text"))

cites <- get_publications(id = "NTzu9c8AAAAJ")
cites <- cites[complete.cases(cites),]
cites <- cites[order(-cites$year),]

formatted <- apply(cites, 1, function(x) paste0(x["author"], ". (", x["year"], "). ", x["title"], ". ", x["journal"], " ", x["number"], ".<br>Citations: <b>", x["cites"], "</b>"))

pandoc.list(formatted, loose = TRUE)
```
